spring:
  datasource:
    url: jdbc:mysql://localhost:3306/els?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 'popshotzs0314'
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:static/
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.syzx.demo.entity
  #自定义枚举类型处理器handler所在包的包名
  type-handlers-package: com.syzx.demo.config
  #configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8081


